---
title: "gradethis examples"
output: learnr::tutorial
runtime: shiny_prerendered
tutorial:
  id: "demo-types"
  version: 1.0
---

```{r}
library(ggplot2)
install.packages("repr")
library(repr)
library(caret)
install.packages("ROCR")
install.packages("openintro")
library(ROCR)
library(pROC)
```



```{r setup, include=FALSE}

library(learnr)
library(gradethis)

total <- function(m) {
  print(paste("Total mark is ",m))
}

mark <- function(m) {
  print(paste("Get mark: ",m))
}
```


## Intro

What is 1+1?
```{r ex1, exercise=TRUE}

```

```{r ex1-solution}
2
```


```{r ex1-check}
total(5)
grade_this({
  ls(all.names=TRUE)
  if (.result == .solution) {
    mark(5)
    
    pass("You got 5 marks!")
  }
  else if (exists("y", envir=.envir_result)){
    y <- get("y", envir = .envir_result)
    if (y==100){
      mark(2)
      fail("You got 2 marks only!")
    }
  }
  
  mark(0)
  fail("Wrong Answer.")
})

#grade_this_code()
```



```{r mc, echo=FALSE}
question("Which of the following interpretations of the bar charts above is NOT valid?",
  answer("Among characters with `Neutral` alignment, males are the most common.", message = "Nope, not quite!"),
  answer("Across all genders, `Bad` is the most common alignment.", correct = TRUE),
  answer("There are more male characters than female characters in this dataset.",  message = "Try again!"), 
  allow_retry = TRUE
)
```

```{r details}
question_text(
  "Student Name:",
  answer(NULL, correct = TRUE),
  incorrect = "Ok",
  try_again_button = "Modify your answer",
  allow_retry = TRUE
)
```






### others


## Preprocessing 

**Exercise**:
Convert the variables `Survived`, `sex` and `Pclass` of the `titanic_train` data frame to factor variables.

```{r to-factor-setup}
#convert the variables to int to simulate the original dataset
titanic_train$Survived<-as.integer(titanic_train$Survived)
titanic_train$Pclass<-as.integer(titanic_train$Pclass)
titanic_train$Sex<-as.character(titanic_train$Sex)
```


```{r to-factor, exercise=TRUE, eval=FALSE}
titanic_train$Survived<-________
titanic_train$Pclass<-_________
titanic_train$Sex<-_________

#Check that the data type of the variables are factor variables.
glimpse(select(titanic_train, Survived, Sex, Pclass))

```

```{r to-factor-solution}
titanic_train$Survived<-factor(titanic_train$Survived)
titanic_train$Pclass<-factor(titanic_train$Pclass)
titanic_train$Sex<-factor(titanic_train$Sex)
```


```{r to-factor-hint, eval=FALSE}
titanic_train$Survived<-factor(______)
titanic_train$Pclass<-factor(_____)
titanic_train$Sex<-factor(______)
```

```{r to-factor-check}
grade_this({
  if (exists("titanic_train", envir=.envir_result))
    titanic_train_result <- get("titanic_train", envir = .envir_result)
    
  glimpse(titanic_train_result)
  if (!is.factor(titanic_train_result$Survived)) 
    fail("Please convert the variable 'Survived' to a factor")
  else if (!is.factor(titanic_train_result$Pclass)) 
    fail("Please convert the variable 'Pclass' to a factor")
  else if (!is.factor(titanic_train_result$Sex)) 
    fail("Please convert the variable 'Sex' to a factor")
  else
    pass()
 }
)
```